export const plans = [
    {
        name: "Free",
        price: 0,
        tagline: "Kickstart your truth checks",
        cta: "Start Free",
        highlight: false,
        bullets: [
            "5 fact checks/day",
            "Images & Videos",
            "2 uploads/check • 10MB each",
            "YouTube up to 10 mins",
        ],
    },
    {
        name: "Plus",
        price: 9.99,
        tagline: "For curious creators",
        cta: "Upgrade to Plus",
        highlight: false,
        bullets: [
            "10 fact checks/day",
            "Image, Video, PDF, Docx",
            "Up to 5 uploads/check • 20MB each",
            "Local video: Unlimited (500MB combined)",
            "YouTube up to 30 mins",
            "SCM short-check (Instagram only)",
        ],
    },
    {
        name: "Pro",
        price: 24.99,
        tagline: "Teams and power users",
        cta: "Go Pro",
        highlight: true,
        bullets: [
            "25 fact checks/day",
            "Image, Video, PDF, Docx, Audio",
            "Up to 10 uploads/check • 50MB each",
            "Local video: Unlimited (1GB combined)",
            "YouTube up to 60 mins",
            "SCM short-check (X, IG, FB, Threads)",
        ],
    },
    {
        name: "Premium",
        price: 34.99,
        tagline: "Scale with confidence",
        cta: "Get Premium",
        highlight: false,
        bullets: [
            "35 fact checks/day",
            "Image, Video, PDF, Docx, Audio",
            "Unlimited uploads (2GB combined)",
            "Max file size: 2GB",
            "Local video: Unlimited (2GB combined)",
            "YouTube up to 8 hours",
            "SCM short-check (X, FB, Threads, IG, Reddit, TikTok)",
        ],
    },
];